spring:
  profiles:    active:    - dev
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  
server:  port: 9090

graphql:
  spqr:
    gui:
      enabled: true